### ISSUE TITLE
[BUG] Console version hardcodes TargetFramework to 16299 for UWP

### ISSUE THREAD

**Issue by harvinders** [reactiveui/Pharmacist#111] opened 2020-02-06 04:26 UTC
**Describe the bug**
Generating events for UWP platform using console hardcodes the TargetPlatform to 16299.

Console app should take another parameter to specify the TargetPlatform

**Steps To Reproduce**
`pharmacist generate-platform -p uwp -o c:\logs\ -output-prefix _Event`

**Additional context**
Should this be applicable for other platforms too?

**Comment by Junocaen** [comment] 2020-05-18 13:30
I can confirm this issue. I've tried to build ReactiveUI.Events and modified the targetframework to uap10.0.18362. The generated uap.cs file from Pharmacist contains a lot uses of deprecated or obsolete classes. I would love to know how to fix this or maybe anyone else can. ReactiveUI.Events is due to this reason not usable in more modern UWP applications.

**Comment by glennawatson** [comment] 2020-05-18 15:57
Yes it's a known issue. It's on my to-do list for sometime soon just have to have a free weekend.

**Comment by Junocaen** [comment] 2020-05-19 07:44
After a little more research. The generated .cs file for UWP did not so many issues after all.  I had  to add the SDKReferences WindowsDesktop and WindowsMobile Extensions for UWP manually. This also solves errors when using any of these api's with ReactiveUI.Events in UWP applications.

**Comment by glennawatson** [comment] 2020-12-07 02:45
Fixed in 2.0.3

**Closed by glennawatson** 2020-12-07 02:45 UTC
Labels: bug
