### ISSUE TITLE
[BUG] Can't get pharmacist to work in an Uno UWP app

### ISSUE THREAD

**Issue by weitzhandler** [reactiveui/Pharmacist#97] opened 2020-01-01 03:13 UTC
I'm trying to get Pharmacist to work on an Uno Platform app.
The app consists of 4 platform-specific projects: UWP, Xamarin.Droid, Xamarin.iOS and WASM (.NET Standard).

[Here](https://github.com/weitzhandler/UnoPharmacist)'s a repro app that contains a newly generated Uno app (using the [Uno Templates Extension](https://marketplace.visualstudio.com/items?itemName=nventivecorp.uno-platform-addin)), whose project files have been modified to add the following two lines before any other `PackageReference` declarations, as of [this](https://github.com/weitzhandler/UnoPharmacist/commit/86426037a1f32a3b50cbd5a10424737418ad2a7d) commit:

```xml
<PackageReference Include="Pharmacist.MsBuild" Version="1.*" PrivateAssets="all" />
<PackageReference Include="Pharmacist.Common" Version="1.*" />
```

When trying to build the project, I'm getting errors such as:
> error MSB4044: The "PharmacistNuGetTask" task was not given a value for the required parameter "TargetFramework".

![image](https://user-images.githubusercontent.com/2716316/71637776-53eb6700-2c55-11ea-82df-1d13dea7676c.png)

**Comment by glennawatson** [comment] 2020-01-01 03:14
Thanks, I'll have a look at it today.

**Comment by glennawatson** [comment] 2020-01-01 06:21
I'm getting some build errors with the project at the moment. Eg for the droid project I am getting:

```
/Users/glennwatson/Downloads/UnoPharmacist-master/UnoPharmacist/UnoPharmacist.Shared/Assets/LockScreenLogo.scale-200.png : warning XA0101: @(Content) build action is not supported
/Users/glennwatson/Downloads/UnoPharmacist-master/UnoPharmacist/UnoPharmacist.Shared/Assets/SplashScreen.scale-200.png : warning XA0101: @(Content) build action is not supported
/Users/glennwatson/Downloads/UnoPharmacist-master/UnoPharmacist/UnoPharmacist.Shared/Assets/Square150x150Logo.scale-200.png : warning XA0101: @(Content) build action is not supported
/Users/glennwatson/Downloads/UnoPharmacist-master/UnoPharmacist/UnoPharmacist.Shared/Assets/Square44x44Logo.scale-200.png : warning XA0101: @(Content) build action is not supported
/Users/glennwatson/Downloads/UnoPharmacist-master/UnoPharmacist/UnoPharmacist.Shared/Assets/Square44x44Logo.targetsize-24_altform-unplated.png : warning XA0101: @(Content) build action is not supported
/Users/glennwatson/Downloads/UnoPharmacist-master/UnoPharmacist/UnoPharmacist.Shared/Assets/StoreLogo.png : warning XA0101: @(Content) build action is not supported
/Users/glennwatson/Downloads/UnoPharmacist-master/UnoPharmacist/UnoPharmacist.Shared/Assets/Wide310x150Logo.scale-200.png : warning XA0101: @(Content) build action is not supported
/Users/glennwatson/Downloads/UnoPharmacist-master/UnoPharmacist/UnoPharmacist.Droid/Properties/AndroidManifest.xml : warning XA4211: AndroidManifest.xml //uses-sdk/@android:targetSdkVersion '26' is less than $(TargetFrameworkVersion) ''. Using API-28 for ACW compilation.
Resources/values/Styles.xml(2): error APT0000: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light'.
Resources/values/Styles.xml(2): error APT0000: No resource found that matches the given name: attr 'windowActionBar'.
Resources/values/Styles.xml(2): error APT0000: No resource found that matches the given name: attr 'windowNoTitle'.
```

The UWP project seems to be working now though with 1.4.1.

**Comment by glennawatson** [comment] 2020-01-01 06:24
Closing the issue since the Droid issues seem unrelated to Pharmacist. Feel free to comment if that is not the case.

**Comment by weitzhandler** [comment] 2020-01-01 06:32
OK, will check about the Droid project, but I actually tried the UWP one.
Try unloading all other projects but the UWP one, it doesn't work either.

**Comment by glennawatson** [comment] 2020-01-01 07:15
UWP is 100% compiling/working for me.

**Comment by glennawatson** [comment] 2020-01-01 07:15
Try doing a NuGet cache clean.

**Comment by glennawatson** [comment] 2020-01-01 07:20
with some of these nuget packages it can take a while to update unless you do a nuget cache clean
you can clean it with dotnet
so like

```
dotnet nuget locals all --clear
```

**Comment by weitzhandler** [comment] 2020-01-02 03:17
Can Pharmacist work on Xamarin.Droid and Xamarin.iOS?

**Comment by glennawatson** [comment] 2020-01-02 03:23
Yep.

**Comment by glennawatson** [comment] 2020-01-02 03:28
You gotta consider the scenario with Xamarin is slightly different, almost everyone has a .net standard 2.0 project for the UI, then just a front end for each platform. So you would put pharmacist in your .net standard 2.0 shared project. Uno seems to like shared projects which are slowly disappearing from Microsoft recommended list.

**Comment by weitzhandler** [comment] 2020-01-02 04:43
Well I can't change the way Uno works.
In a way, this is the advantage of Uno over XF, because it makes a regular UWP app run everywhere.

**Comment by weitzhandler** [comment] 2020-01-02 04:45
But if Pharmacist works on Droid and iOS, it should work. Uno creates to regular Xamarin projects, and just adds another assembly Uno.UI which encapsulates the UWP control API for the current platform, same as for WASM.

**Comment by glennawatson** [comment] 2020-01-02 05:39
Have you tried the instructions above? It has been working with your trial project for me since yesterday.

**Comment by weitzhandler** [comment] 2020-01-02 05:52
I've tried it only with the UWP so far, it did generate the files, but the generated files issued errors. 
It tries to generate `DataContextChanged` event, whereas [`Windows.UI.Xaml.DependencyObject`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.dependencyobject) doesn't have such event.

![image](https://user-images.githubusercontent.com/2716316/71653248-1c072100-2d34-11ea-9b2a-3a727e125ffd.png)

**Comment by weitzhandler** [comment] 2020-01-03 04:32
There was probably a few other issues that didn't let it work. I did try clearing the nuget cache when the problem still occurred. What fixed it for me was deleting the _bin_ and _obj_ folders, deleting the `.vs` folder, and clearing the cache.

**Comment by weitzhandler** [comment] 2020-01-03 04:35
Thanks Glenn for all your help!

**Comment by weitzhandler** [comment] 2020-01-03 12:42
Well look like it's the interactivity library.
Please see my [branch](https://github.com/weitzhandler/UnoPharmacist/tree/behaviors/UnoPharmacist/UnoPharmacist.Droid) targeting that.

**Comment by glennawatson** [comment] 2020-01-05 06:50
The issue is solved in `1.5.3` so do the nuget clear trick and try that.

**Comment by weitzhandler** [comment] 2020-01-06 21:22
Thank you. Yes looks like it's working now.

**Comment by glennawatson** [comment] 2020-01-10 05:19
Re-opening, doesn't seem like the droid project is producing properly.

**Comment by glennawatson** [comment] 2021-05-29 09:55
See https://www.nuget.org/packages/ReactiveMarbles.ObservableEvents.SourceGenerator/ and https://github.com/reactivemarbles/ObservableEventsSourceGenerator

I deliberately included Uno in the testing.

**Closed by glennawatson** 2021-05-29 09:55 UTC
Labels: bug
